name: Deploy Backend & Frontend to AWS EC2

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"
      - "frontend/**"

jobs:
  backend:
    name: Deploy FastAPI Backend
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy Backend
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@18.234.231.208 << 'EOF'
            cd ~/sentiment-api/backend
            git reset --hard
            git clean -fd
            git pull origin main

            docker build -t sentiment-api .
            docker stop sentiment-api || true
            docker rm sentiment-api || true
            docker run -d -p 80:8000 \
              --name sentiment-api \
              --restart unless-stopped \
              sentiment-api
          EOF

  frontend:
    name: Deploy Frontend
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy Frontend
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@18.234.231.208 << 'EOF'
            cd ~/sentiment-api/frontend
            git reset --hard
            git clean -fd
            git pull origin main

            npm install
            npm run build

            sudo rm -rf /var/www/html/*
            sudo cp -r dist/* /var/www/html/
          EOF
